= Databricks setup

include::partial$third-party.adoc[]

== Prerequisites

* A Databricks workspace must be available on an URL like `\https://dbc-xxxxxxxx-yyyy.cloud.databricks.com`.

== Set up a compute cluster

. Create a compute cluster with `Single user` access mode, `Unrestricted` policy, and your preferred Scala runtime.
+
[CAUTION]
====
Shared access modes are not currently supported.
====
. Once the cluster is available, open its page and select the *Libraries* tab.
. Select *Install new* and select *Maven* as the library source.
. Install the connector using either of the following methods:
* Copy the coordinates from the xref:installation.adoc#version[Installation] section (for example `org.neo4j:neo4j-connector-apache-spark_2.12:{exact-connector-version}_for_spark_3`).
* Select *Search Packages* and search the connector on Maven Central (*not* on Spark Packages).

+
[NOTE]
====
Make sure to select the correct version of the connector by matching both the Scala version and the Spark version to the cluster's runtime.
====

=== Unity Catalog

Neo4j supports the Unity Catalog in `Single user` access mode only.
Refer to the link:https://docs.databricks.com/en/compute/access-mode-limitations.html[Databricks documentation] for further information.

== Session configuration

You can set the Spark configuration on the cluster you are running your notebooks on by doing the following:

. Open the cluster configuration page.
. Select the *Advanced Options* toggle under *Configuration*.
. Select the *Spark* tab.

For example, you can add Neo4j Bearer authentication configuration in the text area as follows:

.Bearer authentication example
[source]
----
neo4j.url neo4j://<host>:<port>
neo4j.authentication.type bearer
neo4j.authentication.bearer.token <token>
----

== Authentication methods

All the authentication methods supported by the link:{neo4j-docs-base-uri}/java-manual/current/connect-advanced/#_authentication_methods[Neo4j Java Driver] (version 4.4 and higher) are supported.

See the xref:configuration.adoc#_neo4j_driver_options[Neo4j driver options] for more details on authentication configuration.
