= Installation
:description: This chapter describes the quick way to get started with Neo4j Connector for Apache Spark.

== Download Apache Spark

Download Spark as documented on the link:https://spark.apache.org/downloads.html[Spark website].

== Download the connector

Download the connector JAR file from the link:https://neo4j.com/product/connectors/apache-spark-connector/[Neo4j Connector Page] or from the link:https://github.com/neo4j-contrib/neo4j-spark-connector/releases[GitHub releases page].
The JAR file name has the `neo4j-connector-apache-spark_<Scala version>-<connector version>_for_spark_3.jar` format, for example:

`neo4j-connector-apache-spark_2.12-{exact-connector-version}_for_spark_3.jar`

Make sure to match both the Spark version and the Scala version.
Here is a compatibility table to help you choose the correct JAR.

.Compatibility table
|===
| | Spark 3.0.x and 3.1.x | 3.2.x and above

|*Scala 2.12* |`neo4j-connector-apache-spark_2.12-4.1.5_for_spark_3.jar`
|`neo4j-connector-apache-spark_2.12-{exact-connector-version}_for_spark_3.jar`

|*Scala 2.13* |`neo4j-connector-apache-spark_2.13-4.1.5_for_spark_3.jar`
|`neo4j-connector-apache-spark_2.13-{exact-connector-version}_for_spark_3.jar`
|===

== Run code interactively

With `spark-shell` or `pyspark`:

[shell, subs="attributes+"]
----
$SPARK_HOME/bin/spark-shell --jars neo4j-connector-apache-spark_2.12-{exact-connector-version}_for_spark_3.jar
----

The connector is also available from link:https://spark-packages.org/?q=neo4j-connector-apache-spark[Spark Packages]:

[shell, subs="attributes+"]
----
$SPARK_HOME/bin/spark-shell --packages org.neo4j:neo4j-connector-apache-spark_2.12:{exact-connector-version}_for_spark_3
----

== Develop standalone applications

=== Using sbt

A minimal `build.sbt` file:

.build.sbt
[source, sbt]
----
include::example$scala/build.sbt[]
----

If you use the link:https://github.com/databricks/sbt-spark-package[sbt-spark-package plugin], add the following to your `build.sbt` instead:

[shell, subs="attributes+"]
----
scala spDependencies += "org.neo4j/neo4j-connector-apache-spark_2.12:5.3.0_for_spark_3"
----

=== Using Maven

A minimal `pom.xml` file:

.pom.xml
[source, xml]
----
include::example$java/pom.xml[]
----

=== Using Gradle

[source, `build.gradle`, subs="attributes+"]
----

dependencies{
    // list of dependencies
    compile "org.neo4j:neo4j-connector-apache-spark_2.12:5.3.0_for_spark_3"
}
----
