= Writing to Neo4j

:description: The chapters describes writing methods to a Neo4j database using Neo4j Spark connector.

The following section covers the DataSource Writer and how to transfer the Spark dataset content into Neo4j.
The connector provides batch writes to speed up the ingestion process, so if the process at some point fails, all the previous data are already persisted.

There are two main approaches for writing data to a Neo4j database with the connector:

* <<write-node, Write nodes>> using the `labels` option.
* <<write-rel, Write a relationship>> with source and target nodes using the `relationship` option.

If you need more flexibility, you can also run a xref:write-query.adoc[custom Cypher query] using the `query` option.

[example]
== Example

The following code inserts 10 nodes into Neo4j.
Each node has two labels (`Person` and `Customer`) and four properties (`name`, `surname`, `age`, and `livesIn`).

.Write example
[source,scala]
----
include::example$scala/WriteBasic.scala[tags=!setup]
----

[[save-mode]]
== Save mode

The connector supports two save modes:

* The `Append` mode builds a `CREATE` query.
* The `Overwrite` (default) mode builds a `MERGE` query (requires the `node.keys` option).

[[write-node]]
== Write nodes

With the `labels` option, the connector writes an entire DataFrame as nodes in the Neo4j Database.

The connector builds a `CREATE` or a `MERGE` Cypher query (depending on the <<save-mode, SaveMode>>) that uses the `UNWIND` clause to write a batch of rows (an `events` list with size defined by the `batch.size` option).

The code from the <<example, example>> results in a Cypher query like the following:

|===
|Code|Cypher query

a|
[source, scala]
----
df.write
  .format("org.neo4j.spark.DataSource")
  .mode(SaveMode.Append)
  .option("labels", ":Person:Customer")
  .save()
----

a|
[source, cypher]
----
UNWIND $events AS event
CREATE (n:Person:Customer)
SET n += event.properties
----
|===

With the `Overwrite` mode, you must specify the DataFrame columns to use as keys to match the nodes.
The `node.keys` option takes a comma-separated list of `key:value` pairs, where the key is the DataFrame column name and the value is the node property name.

[NOTE]
====
If `key` and `value` are the same, you can omit the `value`.
For example, `"name:name,surname:surname"` is equivalent to `"name,surname"`.
====

The same code using the `Overwrite` save mode results in a Cypher query like the following:

|===
|Code|Cypher query

a|
[source, scala]
----
df.write
  .format("org.neo4j.spark.DataSource")
  .mode(SaveMode.Overwrite)
  .option("labels", ":Person:Customer")
  .option("node.keys", "name,surname")
  .save()
----

a|
[source, cypher]
----
UNWIND $events AS event
MERGE (n:Person:Customer {
  name: event.keys.name, 
  surname: event.keys.surname
})
SET n += event.properties
----
|===

=== Type mapping

The type mapping between Spark DataFrames and Neo4j is summarized in the xref:types.adoc[] section.

When a column is a map, the connector tries to flatten it.
For example, consider the following dataset:

|===
|id |name |lives_in

|1
|Andrea Santurbano
|{address: 'Times Square, 1', city: 'NY', state: 'NY'}

|2
|Davide Fantuzzi
|{address: 'Statue of Liberty, 10', city: 'NY', state: 'NY'}

|===

The connector flattens the `lives_in` column into three columns `lives_in.address`, `lives_in.city`, and `lives_in.state`:

|===
|id |name |lives_in.address |lives_in.city |lives_in.state

|1
|Andrea Santurbano
|Times Square, 1
|NY
|NY

|2
|Davide Fantuzzi
|Statue of Liberty, 10
|NY
|NY

|===

[[write-rel]]
== Write a relationship

You can write a DataFrame to Neo4j by specifying source, target nodes, and relationships.

[WARNING]
====
To avoid deadlocks, always use a single partition (for example with `coalesce(1)`) before writing relationships to Neo4j.
====

=== Overview

Before diving into the actual process, let's clarify the vocabulary first. Since this method of writing data to Neo4j is more complex and few combinations of options can be used, let's spend more time on explaining it.

In theory you should take your dataset and move the columns around to create source and target nodes,
eventually creating the specified relationships between them.

This is a basic example of what would happen:
[source,cypher]
----
UNWIND $events AS event
CREATE (source:Person)
SET source = event.source
CREATE (target:Product)
SET target = event.target
CREATE (source)-[rel:BOUGHT]->(target)
SET rel += event.rel
----

The `CREATE` keyword for the source and target nodes can be replaced by `MERGE` or `MATCH`.
To control this you can use the <<node-save-modes,Node save modes>>.

You can set source and target nodes independently by using `relationship.source.save.mode` or `relationship.target.save.mode`.

These options accept a case insensitive string as a value, that can be one of `ErrorIfExists`, `Overwrite`, `Append`;
they work in the same same way as the <<write-node,Node save modes>>.

When using `MATCH` or `MERGE`, you need to specify keys that identify the nodes.
This is what the options `relationship.source.node.keys` and `relationship.target.node.keys`.
More on this <<rel-specify-keys,here>>.

The `CREATE` keyword for the relationship can be replaced by a `MERGE`.
You can control this with <<save-mode,Save mode>>.

You are also required to specify one of the two <<strategies,Save Strategies>>.
This identifies which method is to be used to create the Cypher query
and can have additional options available.

[[strategies]]
=== Save strategies

There are two strategies you can use to write relationships: <<strategy-native,Native>> (default strategy) and <<strategy-keys,Keys>>.

[[strategy-native]]
==== Native strategy

The Native strategy is useful when you have a schema that conforms with the <<reading.adoc#rel-schema-no-map,Relationship read schema>>, and the `relationship.nodes.map` set to false.

If you want to read relationship from a database, filter data, and write the result to another database, you can refer to the following example:

[source,scala]
----
import org.apache.spark.sql.{SaveMode, SparkSession}

val spark = SparkSession.builder().getOrCreate()

val originalDf = spark.read.format("org.neo4j.spark.DataSource")
  .option("url", "neo4j://allprod.host.com:7687")
  .option("relationship", "BOUGHT")
  .option("relationship.nodes.map", "false")
  .option("relationship.source.labels", "Person")
  .option("relationship.target.labels", "Product")
  .load()

originalDf
    .where("`target.price` > 2000")
    .write
    .format("org.neo4j.spark.DataSource")
    .option("url", "neo4j://expensiveprod.host.com:7687")
    .option("relationship", "SOLD")
    .option("relationship.source.labels", ":Person:Rich")
    .option("relationship.source.save.mode", "ErrorIfExists")
    .option("relationship.target.labels", ":Product:Expensive")
    .option("relationship.target.save.mode", "ErrorIfExists")
    .save()
----

You just need to specify the source node labels, the target node labels, and the relationship you want between them.

The generated query is the following:
[source,cypher]
----
UNWIND $events AS event
CREATE (source:Person:Rich)
SET source = event.source
CREATE (target:Product:Expensive)
SET target = event.target
CREATE (source)-[rel:BOUGHT]->(target)
SET rel += event.rel
----

`event.source`, `event.target`, and `event.rel` contain the column described <<reading.adoc#rel-schema-columns,here>>.

[NOTE]
The default save mode for source and target nodes is `Match`.
That means that the relationship can be created only if the nodes are already in your database.
Look at <<node-save-modes,here>> for more information on node save modes.

When using `Overwrite` or `Match` node save mode, you should specify which keys should be used to identify the nodes.

.The DataFrame we are working with
|===
|<rel.id>|<rel.type>|<source.id>|<source.labels>|source.id|source.fullName|<target.id>|<target.labels>|target.name|target.id|rel.quantity

|4|BOUGHT|1|[Person]|1|John Doe|0|[Product]|Product 1|52|240
|5|BOUGHT|3|[Person]|2|Jane Doe|2|[Product]|Product 2|53|145
|===

[source,scala]
----
import org.apache.spark.sql.{SaveMode, SparkSession}

val spark = SparkSession.builder().getOrCreate()

// we read our DF from Neo4j using the relationship method
val df = spark.read.format("org.neo4j.spark.DataSource")
  .option("url", "neo4j://first.host.com:7687")
  .option("relationship", "BOUGHT")
  .option("relationship.nodes.map", "false")
  .option("relationship.source.labels", "Person")
  .option("relationship.target.labels", "Product")
  .load()

df.write
  .format("org.neo4j.spark.DataSource")
  .option("url", "neo4j://second.host.com:7687")
  .option("relationship", "SOLD")
  .option("relationship.source.labels", ":Person:Rich")
  .option("relationship.source.save.mode", "Overwrite")
  .option("relationship.source.node.keys", "source.fullName:fullName")
  .option("relationship.target.labels", ":Product:Expensive")
  .option("relationship.target.save.mode", "Overwrite")
  .option("relationship.target.node.keys", "target.id:id")
  .save()
----

You must specify which columns of your DataFrame are being used as keys to match the nodes.
You control this with the options `relationship.source.node.keys` and `relationship.target.node.keys`, specifying a comma-separated list of `key:value` pairs,
where the key is the DataFrame column name, and the value is the node property name.

The generated query is the following:
[source,cypher]
----
UNWIND $events AS event
MERGE (source:Person:Rich {fullName: event.source.fullName})
SET source = event.source
MERGE (target:Product:Expensive {id: event.target.id})
SET target = event.target
CREATE (source)-[rel:BOUGHT]->(target)
SET rel += event.rel
----

[NOTE]
Remember that you can choose to `CREATE` or `MERGE` the relationship with the <<save-mode,Save mode>>.

[NOTE]
If the provided DataFrame schema doesn't conform to the required schema, meaning that none of the required columns is present,
the write fails.

[[strategy-keys]]
==== Keys strategy

When you want more control over the relationship writing, you can use the *Keys* strategy.

As in the case of using the Native strategy, you can specify node keys to identify nodes.
In addition, you can also specify which columns should be written as nodes properties.

[[rel-specify-keys]]
.Specify keys
[source,scala]
----
import org.apache.spark.sql.{SaveMode, SparkSession}

val spark = SparkSession.builder().getOrCreate()
import spark.implicits._

val musicDf = Seq(
        (12, "John Bonham", "Drums"),
        (19, "John Mayer", "Guitar"),
        (32, "John Scofield", "Guitar"),
        (15, "John Butler", "Guitar")
    ).toDF("experience", "name", "instrument")

musicDf.coalesce(1)
    .write
    .format("org.neo4j.spark.DataSource")
    .option("url", "neo4j://localhost:7687")
    .option("relationship", "PLAYS")
    .option("relationship.save.strategy", "keys")
    .option("relationship.source.labels", ":Musician")
    .option("relationship.source.save.mode", "overwrite")
    .option("relationship.source.node.keys", "name:name")
    .option("relationship.target.labels", ":Instrument")
    .option("relationship.target.node.keys", "instrument:name")
    .option("relationship.target.save.mode", "overwrite")
    .save()
----

This creates a `MERGE` query using `name` property as key for `Musician` nodes.
The value of `instrument` column is used as a value for `Instrument` property `name`, generating a statement like:

`MERGE (target:Instrument {name: event.target.instrument})`.

Here you must specify which columns of your DataFrame will be written in the source node and in the target node properties.
You can do this with the options `relationship.source.node.properties` and `relationship.target.node.properties`,
specifying a comma-separated list of `key:value` pairs, where the key is the DataFrame column name,
and the value is the node property name.

Same applies to `relationship.properties` option, used to specify which DataFrame columns are written as relationship properties.

[NOTE]
If `key` and `value` are the same field you can specify one without the colon.
For example, if you have `.option("relationship.source.node.properties", "name:name,email:email")`, you can also write
`.option("relationship.source.node.properties", "name,email")`.
Same applies for `relationship.source.node.keys` and `relationship.target.node.keys`.

.Specify properties and keys
[source,scala]
----
import org.apache.spark.sql.{SaveMode, SparkSession}

val spark = SparkSession.builder().getOrCreate()
import spark.implicits._

val musicDf = Seq(
        (12, "John Bonham", "Orange", "Drums"),
        (19, "John Mayer", "White", "Guitar"),
        (32, "John Scofield", "Black", "Guitar"),
        (15, "John Butler", "Wooden", "Guitar")
    ).toDF("experience", "name", "instrument_color", "instrument")

musicDf.coalesce(1)
    .write
    .format("org.neo4j.spark.DataSource")
    .option("url", "neo4j://localhost:7687")
    .option("relationship", "PLAYS")
    .option("relationship.save.strategy", "keys")
    .option("relationship.source.labels", ":Musician")
    .option("relationship.source.save.mode", "overwrite")
    .option("relationship.source.node.keys", "name:name")
    .option("relationship.target.labels", ":Instrument")
    .option("relationship.target.node.keys", "instrument:name")
    .option("relationship.target.node.properties", "instrument_color:color")
    .option("relationship.target.save.mode", "overwrite")
    .save()
----

[[node-save-modes]]
==== Node save modes

You can specify four different modes for saving the nodes:

* `Overwrite` mode performs a `MERGE` on that node.
* `ErrorIfExists` mode performs a `CREATE` (not available for Spark 3).
* `Append` mode performs a `CREATE` (not available for Spark 2.4).
* `Match` mode performs a `MATCH`.

[NOTE]
For `Overwrite` mode you *must have unique constraints on the keys*.

== Performance considerations

Since writing is typically an expensive operation, make sure you write only the columns you need from the DataFrame.
For example, if the columns from the data source are `name`, `surname`, `age`, and `livesIn`, but you only need `name` and `surname`, you can do the following:

[source, scala]
----
ds.select(ds("name"), ds("surname"))
  .write
  .format("org.neo4j.spark.DataSource")
  .mode(SaveMode.ErrorIfExists)
  .option("url", "neo4j://localhost:7687")
  .option("labels", ":Person:Customer")
  .save()
----

== Note about columns with Map type

When a Dataframe column is a map, what we do internally is to flatten the map as Neo4j does not support this type for graph entity properties; so for a Spark job like this:

[source,scala]
----
val data = Seq(
  ("Foo", 1, Map("inner" -> Map("key" -> "innerValue"))),
  ("Bar", 2, Map("inner" -> Map("key" -> "innerValue1"))),
).toDF("id", "time", "table")

data.write
  .mode(SaveMode.Append)
  .format(classOf[DataSource].getName)
  .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
  .option("labels", ":MyNodeWithFlattenedMap")
  .save()
----

In Neo4j for the nodes with label `MyNodeWithFlattenedMap` you'll find this information stored:

----
MyNodeWithFlattenedMap {
    id: 'Foo',
    time: 1,
    `table.inner.key`: 'innerValue'
}
MyNodeWithFlattenedMap {
    id: 'Bar',
    time: 1,
    `table.inner.key`: 'innerValue1'
}
----

Now you could fall into problematic situations like the following one:

[source,scala]
----
val data = Seq(
  ("Foo", 1, Map("key.inner" -> Map("key" -> "innerValue"), "key" -> Map("inner.key" -> "value"))),
  ("Bar", 1, Map("key.inner" -> Map("key" -> "innerValue1"), "key" -> Map("inner.key" -> "value1"))),
).toDF("id", "time", "table")
data.write
  .mode(SaveMode.Append)
  .format(classOf[DataSource].getName)
  .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
  .option("labels", ":MyNodeWithFlattenedMap")
  .save()
----

since the resulting flattened keys are duplicated, the Neo4j Spark will pick one of the associated value in a non-deterministic way.

Because the information that we'll store into Neo4j will be this (consider that the order is not guaranteed):

----
MyNodeWithFlattenedMap {
    id: 'Foo',
    time: 1,
    `table.key.inner.key`: 'innerValue' // but it could be `value` as the order is not guaranteed
}
MyNodeWithFlattenedMap {
    id: 'Bar',
    time: 1,
    `table.key.inner.key`: 'innerValue1' // but it could be `value1` as the order is not guaranteed
}
----

== Group duplicated keys to array of values

You can use the option `schema.map.group.duplicate.keys` to avoid this problem. The connector will group all the values with the same keys into an array. The default value for the option is `false`.
In a scenario like this:

[source,scala]
----
val data = Seq(
  ("Foo", 1, Map("key.inner" -> Map("key" -> "innerValue"), "key" -> Map("inner.key" -> "value"))),
  ("Bar", 1, Map("key.inner" -> Map("key" -> "innerValue1"), "key" -> Map("inner.key" -> "value1"))),
).toDF("id", "time", "table")
data.write
  .mode(SaveMode.Append)
  .format(classOf[DataSource].getName)
  .option("url", SparkConnectorScalaSuiteIT.server.getBoltUrl)
  .option("labels", ":MyNodeWithFlattenedMap")
  .option("schema.map.group.duplicate.keys", true)
  .save()
----

the output would be:

----
MyNodeWithFlattenedMap {
    id: 'Foo',
    time: 1,
    `table.key.inner.key`: ['innerValue', 'value'] // the order is not guaranteed
}
MyNodeWithFlattenedMap {
    id: 'Bar',
    time: 1,
    `table.key.inner.key`: ['innerValue1', 'value1'] // the order is not guaranteed
}
----

