= Read nodes

include::partial$sparksession.adoc[]

You can read nodes by specifying one or more labels with the `labels` option.

For example, given a graph with `Person` nodes, you can run the following code to get a DataFrame containing all `Person` nodes with their node properties.

.Basic read operation

[source, scala]
----
val df = spark.read
  .format("org.neo4j.spark.DataSource")
  .option("labels", ":Person")
  .load()
  
df.show()
----

.Result
|===
|<id>|<labels>|surname|name|age

|0|[Person, Customer]|Doe|Jane|40
|39|[Person, Customer]|Doe|John|42
|===

You can specify multiple labels using the colon as a separator.
The colon before the first label is optional.

.Multiple labels
[source,scala]
----
val df = spark.read
  .format("org.neo4j.spark.DataSource")
  // ":Person:Customer" and "Person:Customer"
  // are equivalent
  .option("labels", ":Person:Customer")
  .load()

df.show()
----

.Result
|===
|<id>|<labels>|surname|name|age

|0|[Person, Customer]|Doe|Jane|40
|39|[Person, Customer]|Doe|John|42
|===

== DataFrame columns

When reading data with this method, the resulting DataFrame contains as many columns as the number of node properties plus two additional columns:

* `<id>`: internal Neo4j ID
* `<labels>`: list of labels for each node

== Schema

If the link:{neo4j-docs-base-uri}/apoc/current/[APOC library] is available on the Neo4j instance, the schema is retrieved via the link:{neo4j-docs-base-uri}/apoc/current/overview/apoc.meta/apoc.meta.nodeTypeProperties/[`apoc.meta.nodeTypeProperties`^] procedure.
Otherwise, the following Cypher query is executed:

[source, cypher]
----
MATCH (n:<labels>) <1>
RETURN n
ORDER BY rand()
LIMIT <limit> <2>
----
<1> `<labels>` is the list of labels provided by the `labels` option.
<2> `<limit>` is the value provided by the `schema.flatten.limit` option.

The schema is recreated from the flattened query result.

=== Example

[source, cypher]
----
CREATE (p1:Person {age: 40, name: 'Jane Doe'}),
    (p2:Person {name: 'John Doe', age: 42, location: null}),
    (p3:Person {age: 25, location: point({latitude: -37.659560, longitude: -68.178060})})
----

The following schema is created:

|===
|Field |Type

|<id>|Int

|<labels>|String[]

|age|Int

|name|String

|location|Point

|===